package com.sforce.soap.enterprise;

/** * Generated by SimpleTypeGenerator.java. Please do not edit. */
public enum LayoutComponentType {
	/** * Enumeration : Field */
	Field, /** * Enumeration : Separator */
	Separator, /** * Enumeration : SControl */
	SControl, /** * Enumeration : EmptySpace */
	EmptySpace,
}